/**
 * OAuth Preflight & Resilience Utilities for Supabase GoTrue
 *
 * Prevents unconditional browser redirects to unconfigured OAuth providers,
 * avoiding raw HTTP 400 Bad Request JSON error screens.
 */

export class OAuthProviderDisabledError extends Error {
  readonly provider: string;
  readonly code: string = 'oauth_provider_disabled';

  constructor(provider: string, message?: string) {
    super(message || `OAuth provider '${provider}' is not enabled on this Supabase instance.`);
    this.name = 'OAuthProviderDisabledError';
    this.provider = provider;
    Object.setPrototypeOf(this, OAuthProviderDisabledError.prototype);
  }
}

interface SettingsCacheEntry {
  data: {
    external?: Record<string, boolean>;
    [key: string]: any;
  };
  timestamp: number;
}

const SETTINGS_CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes in ms
const settingsCache = new Map<string, SettingsCacheEntry>();

/**
 * Clear the in-memory settings cache. Primarily used in unit tests.
 */
export function clearSettingsCache(): void {
  settingsCache.clear();
}

/**
 * Checks whether an OAuth provider is actively enabled on the Supabase GoTrue backend.
 * Queries the public `/auth/v1/settings` endpoint and caches the result for 5 minutes.
 *
 * @param supabaseUrl The base Supabase instance URL (e.g. https://xyz.supabase.co)
 * @param anonKey The public Supabase anon key
 * @param provider The OAuth provider identifier (e.g. 'google', 'apple', 'github')
 * @param forceRefresh If true, bypasses the 5-minute in-memory cache
 * @returns Promise<boolean> True if the provider is explicitly enabled, false otherwise
 */
export async function isOAuthProviderEnabled(
  supabaseUrl: string,
  anonKey: string,
  provider: string,
  forceRefresh = false
): Promise<boolean> {
  const cleanUrl = supabaseUrl.replace(/\/+$/, '');
  const cacheKey = `${cleanUrl}::${anonKey}`;
  const now = Date.now();

  const cached = settingsCache.get(cacheKey);
  if (!forceRefresh && cached && (now - cached.timestamp) < SETTINGS_CACHE_TTL_MS) {
    return Boolean(cached.data?.external?.[provider]);
  }

  try {
    const endpoint = `${cleanUrl}/auth/v1/settings?apikey=${encodeURIComponent(anonKey)}`;
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 3500);

    const res = await fetch(endpoint, {
      method: 'GET',
      headers: {
        apikey: anonKey,
      },
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    if (!res.ok) {
      console.warn(`[oauthPreflight] /auth/v1/settings returned HTTP ${res.status}`);
      return false;
    }

    const data = await res.json();
    settingsCache.set(cacheKey, { data, timestamp: now });
    return Boolean(data?.external?.[provider]);
  } catch (err: any) {
    console.warn('[oauthPreflight] Failed to fetch Supabase auth settings:', err?.message || err);
    return false;
  }
}

/**
 * Probes a Supabase GoTrue authorization URL with a manual redirect GET request.
 * If the provider is disabled, Supabase returns HTTP 400 Bad Request with validation_failed.
 *
 * @param authorizeUrl The authorization URL generated by supabase.auth.signInWithOAuth
 * @returns Promise<{ ok: boolean; status?: number; error?: string }>
 */
export async function probeAuthorizeUrl(
  authorizeUrl: string
): Promise<{ ok: boolean; status?: number; error?: string }> {
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 3500);

    const res = await fetch(authorizeUrl, {
      method: 'GET',
      redirect: 'manual',
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    // Opaque redirect (type === 'opaqueredirect', status === 0) or 302 or 2xx means valid redirect/response
    if (res.type === 'opaqueredirect' || res.status === 0 || res.status === 302 || (res.status >= 200 && res.status < 300)) {
      return { ok: true, status: res.status };
    }

    // HTTP 400 Bad Request indicates provider disabled or validation error
    if (res.status === 400) {
      let errorMsg = 'Unsupported provider: provider is not enabled';
      try {
        const body = await res.json();
        errorMsg = body.msg || body.error_description || body.error_code || errorMsg;
      } catch {
        // use fallback string
      }
      return { ok: false, status: 400, error: errorMsg };
    }

    // Any other status: inspect body for validation_failed or provider not enabled
    try {
      const body = await res.json();
      if (body?.error_code === 'validation_failed' || body?.msg?.includes('not enabled')) {
        return { ok: false, status: res.status, error: body.msg || 'validation_failed' };
      }
    } catch {
      // not JSON
    }

    return { ok: false, status: res.status, error: `HTTP ${res.status}` };
  } catch (err: any) {
    console.warn('[oauthPreflight] Authorize URL probe error:', err?.message || err);
    return { ok: false, error: err?.message || 'Network probe failed' };
  }
}
