const fs = require('fs');

const lessonPath = 'courses/medchem/lessons/lesson-10.json';
const lesson = JSON.parse(fs.readFileSync(lessonPath, 'utf8'));

// Step 1: Predict & Reveal
lesson.steps[0].conceptCheck.options[1].text = {
  tr: "Parasetamol doğrudan santral COX enzimlerini kalıcı olarak bloke etmiş; prostaglandin sentezinin sıfırlanmasıyla mide ve damar perfüzyonu çökmüştür.",
  ar: "قام الباراسيتامول بتثبيط إنزيمات COX المركزية بشكل دائم، مما أوقف البروستاغلاندين وسبب انهيار التروية الدموية.",
  en: "Paracetamol irreversibly blocks central and peripheral COX enzymes, obliterating prostaglandin synthesis and collapsing systemic perfusion."
};
lesson.steps[0].conceptCheck.options[1].misconceptionFeedback = {
  tr: "COX blokajı yanılgısı: Parasetamolün analjezik/antipiretik etkisi santral COX inhibisyonuna dayanır ancak bu mekanizma ölümcül değildir; hepatotoksisitenin tek nedeni CYP2E1 ile oluşan reaktif elektrofilik metabolit NAPQI'dir.",
  ar: "مغالطة تثبيط COX: التأثير المسكن يعتمد على تثبيط COX، لكن السمية الكبدية القاتلة تنشأ حصراً من تشكل المستقلب الإلكتروفيلي التفاعلي NAPQI بواسطة CYP2E1.",
  en: "COX inhibition fallacy: Analgesia stems from central COX inhibition, but lethal hepatotoxicity is strictly caused by the electrophilic reactive metabolite NAPQI generated by CYP2E1."
};

lesson.steps[0].conceptCheck.options[2].text = {
  tr: "Aşırı dozda ana parasetamol molekülü değişmeden hepatosit nükleusuna girerek doğrudan DNA zincirlerine interkale olup hücreleri öldürmüştür.",
  ar: "دخلت جزيئات الباراسيتامول السليمة دون استقلاب إلى نواة الخلايا الكبدية واندست مباشرة في شريط DNA مسببة الموت الخلوي.",
  en: "Intact unchanged paracetamol accumulates in hepatocyte nuclei and intercalates directly into genomic DNA to trigger acute cellular lysis."
};
lesson.steps[0].conceptCheck.options[2].misconceptionFeedback = {
  tr: "Doğrudan intakt ilaç toksisitesi yanılgısı: Parasetamol molekülünün kendisi hepatotoksik veya DNA interkalatörü değildir; toksisite ancak ana ilacın CYP2E1 enzimiyle reaktif elektrofilik NAPQI'ye biyotransforme olmasıyla başlar.",
  ar: "مغالطة السمية المباشرة للدواء الأصلي: الباراسيتامول السليم غير سام بحد ذاته؛ السمية تتطلب التحول الحيوي عبر CYP2E1 إلى المركب الإلكتروفيلي NAPQI.",
  en: "Direct parent toxicity fallacy: Intact paracetamol is biologically inert to DNA; toxicity strictly requires enzymatic bioactivation by CYP2E1 into electrophilic NAPQI."
};

// Step 2: Question
lesson.steps[1].conceptCheck.options[1].text = {
  tr: "Fenolik -OH grubu yüksek dozda sterik engele uğrar; SULT enzimi aromatik halkaları tanıyamaz hale gelirken UGT yalnızca alifatik zincirlere bağlanır.",
  ar: "تتعرض مجموعة الفينول لإعاقة فراغية بالجرعات العالية، فيعجز SULT عن تمييز الحلقات العطرية بينما يختص UGT بالسلاسل الأليفاتية.",
  en: "High drug concentrations induce steric hindrance at the phenolic ring, preventing SULT binding while UGT selectively targets aliphatic chains."
};
lesson.steps[1].conceptCheck.options[1].misconceptionFeedback = {
  tr: "Substrat özgüllüğü yanılgısı: Hem SULT hem UGT fenolik -OH gruplarını mükemmel tanır; yolak baskınlığındaki değişim sterik engelden değil, enzimlerin Km değerleri ve hücre içi kofaktör (PAPS vs UDPGA) kapasitesinden kaynaklanır.",
  ar: "مغالطة نوعية الركيزة: يتعرف كلا الإنزيمين على الفينول بكفاءة؛ التبدل يعود لقيم Km وسعة المخزون الخلوي للمرافقات الإنزيمية (PAPS مقابل UDPGA).",
  en: "Substrate selectivity misconception: Both enzymes efficiently conjugate phenols; pathway shifting is driven by differential Km values and intracellular cofactor reserves (PAPS vs UDPGA)."
};

lesson.steps[1].conceptCheck.options[2].text = {
  tr: "Sülfat konjugatları kanda kararsızdır; yüksek ilaç derişiminde kimyasal denge geri döner ve sülfatlar hızla hidroliz edilerek serbest ilaca dönüşür.",
  ar: "مركبات الكبريتات غير مستقرة بالدم؛ عند التراكيز العالية ينعكس التوازن الكيميائي وتتحلمه الكبريتات بسرعة محررة الدواء الأصلي.",
  en: "Sulfate conjugates are chemically unstable in circulation; elevated drug concentrations shift equilibrium toward spontaneous back-hydrolysis into parent paracetamol."
};
lesson.steps[1].conceptCheck.options[2].misconceptionFeedback = {
  tr: "Geri hidroliz yanılgısı: Parasetamol sülfat kovalent bağlı son derece kararlı bir metabolittir ve kanda kendiliğinden hidroliz olmaz; düşük dozda baskın olmasının nedeni yüksek afinite (düşük Km), yüksek dozda doymasının nedeni ise kısıtlı PAPS havuzudur.",
  ar: "مغالطة الحلمهة العكسية: كبريتات الباراسيتامول مركب تساهمي مستقر للغاية لا يتحلمه في الدم؛ سيطرة المسار بالجرع المنخفضة سببها الألفة العالية ونفاذ PAPS لاحقاً.",
  en: "Reverse hydrolysis fallacy: Paracetamol sulfate is a highly stable covalent metabolite in plasma; saturation arises from stoichiometric depletion of PAPS cofactors."
};

// Step 3: Intuition
lesson.steps[2].conceptCheck.options[1].text = {
  tr: "Kapasite aşılınca karaciğer değişmemiş lipofilik ilacı hızla safra kanallarına pompalar ve enterohepatik döngüyle tüm ilaç feçesle atılır.",
  ar: "عند تجاوز السعة، يضخ الكبد الدواء غير المتغير إلى القنوات الصفراوية ليُطرح تماماً عبر الدوران المعوي الكبدي في البراز.",
  en: "Upon capacity overload, hepatocytes actively pump unconjugated lipophilic drug into bile canaliculi for complete elimination in feces via enterohepatic recirculation."
};
lesson.steps[2].conceptCheck.options[1].misconceptionFeedback = {
  tr: "Enterohepatik kaçış yanılgısı: Lipofilik ksenobiyotikler konjuge edilmeden safraya verimli bir şekilde atılamaz; safraya atılan metabolitler çoğunlukla polar glukuronitlerdir. Ana ilaç kanda dolaşmaya devam eder ve CYP2E1 ile oksitlenir.",
  ar: "مغالطة الطرح الصفراوي: لا يمكن طرح الأدوية المحبة للدهون في الصفراء دون اقتران قطبي؛ الدواء الحر غير المقترن يبقى في الدم ليتأكسد عبر CYP2E1.",
  en: "Biliary clearance misconception: Lipophilic xenobiotics cannot be efficiently eliminated in bile without polar conjugation; excess drug remains circulating and enters CYP2E1 oxidation."
};

lesson.steps[2].conceptCheck.options[2].text = {
  tr: "Karaciğer enzimleri doyunca böbrek glomerülleri filtre etme kapasitesini 50 kat artırarak değişmemiş serbest ilacı hızla idrara süzer.",
  ar: "عند تشبع إنزيمات الكبد، تضاعف الكبيبات الكلوية سعة الترشيح 50 ضعفاً لتصفية الدواء الحر غير المتغير في البول بسرعة.",
  en: "Once hepatic enzymes saturate, glomerular filtration upregulates 50-fold to eliminate the excess lipophilic paracetamol unchanged directly in urine."
};
lesson.steps[2].conceptCheck.options[2].misconceptionFeedback = {
  tr: "Böbrek kompanzasyonu yanılgısı: Parasetamol zayıf lipofiliktir ve böbrek tübüllerinden pasif olarak geri emilir; idrarla atılabilmesi için mutlaka Faz II enzimleri (özellikle UGT) tarafından polar bir konjugata çevrilmesi şarttır.",
  ar: "مغالطة التعويض الكلوي: الباراسيتامول محب للدهون جزئياً ويُعاد امتصاصه عبر الأنابيب الكلوية؛ التخلص منه في البول يتطلب حتماً تحويله لمشتق قطبي مقترن عبر UGT.",
  en: "Renal compensation fallacy: Unconjugated paracetamol is passively reabsorbed across renal tubules; rapid urinary clearance strictly requires conversion to polar Phase II conjugates."
};

// Step 4: Visual Explanation
lesson.steps[3].conceptCheck.options[1].text = {
  tr: "N4-Asetil türevi idrardaki kalsiyum ve magnezyum iyonlarını şelatlayarak çözünmeyen inorganik taş kompleksleri oluşturur.",
  ar: "يشلب مشتق N4-أسيتيل أيونات الكالسيوم والمغنيسيوم في البول مشكلاً معقدات حصوية غير قابلة للذوبان.",
  en: "The N4-acetyl derivative chelates urinary calcium and magnesium cations, precipitating insoluble inorganic mineral complexes."
};
lesson.steps[3].conceptCheck.options[1].misconceptionFeedback = {
  tr: "Şelasyon ve taş tipi yanılgısı: Kristalüri bir kalsiyum taşı değildir; ilacın primer amin grubunun nötr amite dönüşmesiyle asidik idrarda çözünürlüğünü kaybetmesinden doğan doğrudan organik kristal çökmesidir.",
  ar: "مغالطة التشليب المعدني: البلورات ليست حصى كالسيوم؛ بل هي ترسب مباشر للمركب العضوي بعد فقدانه القطبية وتحول الأمين إلى أميد متعادل في بول حمضي.",
  en: "Cation chelation misconception: Crystalluria is not a mineral calcium stone; it is direct organic precipitation caused by converting a basic amine into a neutral, poorly soluble amide."
};

lesson.steps[3].conceptCheck.options[2].text = {
  tr: "Karaciğer enzimleri sülfonamid kükürdünü sülfona oksitler; bu sülfon türevi tübül epitelindeki proteinlerle kovalent çapraz bağ kurar.",
  ar: "تؤكسد إنزيمات الكبد كبريت السلفوناميد إلى سلفون؛ ويرتبط هذا المشتق تساهمياً مع بروتينات الظهارة النبيبية.",
  en: "Hepatic enzymes oxidize sulfonamide sulfur into an insoluble sulfone that covalently cross-links with tubular epithelial membrane proteins."
};
lesson.steps[3].conceptCheck.options[2].misconceptionFeedback = {
  tr: "Kükürt oksidasyonu yanılgısı: Kristalüriye yol açan metabolizma S-oksidasyon değil, para-amino grubunun NAT-2 ile N-asetilasyonudur; oluşan N4-asetilsülfadiazin asidik idrarda polaritesini kaybederek çöker.",
  ar: "مغالطة أكسدة الكبريت: المسؤول عن البلورات هو تفاعل N-أسيتيل عبر NAT-2 للأمين العطري وليس أكسدة الكبريت؛ حيث يفقد المشتق انحلاليته في البول الحمضي.",
  en: "Sulfur oxidation fallacy: Crystalluria is caused by NAT-2 N-acetylation of the aromatic amino group, not S-oxidation; the resulting N4-acetyl derivative loses solubility at acidic urine pH."
};

// Step 6: Guided Discovery
lesson.steps[5].conceptCheck.options[1].text = {
  tr: "Üç amino asitlik intakt GSH konjugatı hiç parçalanmadan glomerüllerden doğrudan süzülür; tübüler peptidazlara ihtiyaç duyulmaz.",
  ar: "يُرشح معقد GSH الثلاثي السليم بالكامل عبر الكبيبات الكلوية مباشرة دون الحاجة لأي إنزيمات ببتيداز نبيبية.",
  en: "The intact tripeptide GSH conjugate is filtered directly across glomeruli into urine without requiring tubular peptidolysis."
};
lesson.steps[5].conceptCheck.options[1].misconceptionFeedback = {
  tr: "Budadan doğrudan atılım yanılgısı: GSH konjugatı 500 Da'dan büyük hantal bir yapıdır; proksimal tübüllerde gama-glutamiltranspeptidaz ve dipeptidaz ile glutamat ve glisin koparılıp amino asitler geri kazanılmadan idrarla atılamaz.",
  ar: "مغالطة الطرح المباشر: معقد GSH جزيء ضخم؛ تقوم إنزيمات gGT والديببتيداز النبيبية بنزع الجلوتامات والجليسين لإعادة تدويرهما قبل تكوين حمض الميركابتوريك.",
  en: "Direct excretion fallacy: GSH conjugates are large tripeptides; proximal tubule gGT and dipeptidases sequentially cleave glutamate and glycine to salvage amino acids prior to mercapturic acid excretion."
};

lesson.steps[5].conceptCheck.options[2].text = {
  tr: "Hücresel peptidazlar sistein kükürt-karbon (C-S) bağını kopararak ilacı intakt formda serbest bırakır ve ksenobiyotiği geri dönüştürür.",
  ar: "تكسر ببتيدازات الخلية رابطة الكبريت-كربون (C-S) لتحرر الدواء سليماً في العصارة الخلوية وتعيد تدويره.",
  en: "Intracellular peptidases cleave the cysteine-drug C-S bond, regenerating the parent xenobiotic intact for metabolic recycling."
};
lesson.steps[5].conceptCheck.options[2].misconceptionFeedback = {
  tr: "C-S klivajı yanılgısı: Ksenobiyotik ile sistein arasındaki C-S tiyoeter bağı son derece dayanıklıdır ve hidrolize uğramaz; molekül serbest ilaca dönüştürülmez, N-asetillenerek merkaptürik asit halinde elimine edilir.",
  ar: "مغالطة فك رابطة C-S: رابطة الثيوايثر بين الدواء والسيستين شديدة الاستقرار؛ لا يتحرر الدواء بل تتم أسيتلة السيستين ليطرح كحمض ميركابتوريك.",
  en: "C-S cleavage fallacy: The xenobiotic thioether bond is highly stable and not cleaved by peptidases; the cysteine conjugate is acetylated into mercapturic acid for terminal excretion."
};

// Step 7: Formal Explanation
lesson.steps[6].conceptCheck.options[1].text = {
  tr: "Hızlı asetilatörlerde intestinal P-glikoprotein (P-gp) aşırı eksprese edilmiştir; ilaç emilmeden feçesle dışarı atılır.",
  ar: "يفرط التعبير عن مضخات P-glycoprotein في أمعاء المفرزين السريعين، مما يطرح الدواء في البراز دون امتصاصه.",
  en: "Rapid acetylators overexpress intestinal P-glycoprotein (P-gp) efflux pumps, preventing drug absorption by expelling it directly into feces."
};
lesson.steps[6].conceptCheck.options[1].misconceptionFeedback = {
  tr: "Efluks pompası yanılgısı: İzoniyazid emilimi hızlı ve tamdır; plazma konsantrasyonu farkı bağırsak taşınmasından değil, karaciğerdeki sitozolik NAT-2 enziminin genetik delesyon veya mutasyonlarından kaynaklanır.",
  ar: "مغالطة مضخات الطرد: امتصاص الإيزونيازيد تام وسريع؛ الفروق البلازمية تعود لطفرات جينية في إنزيم NAT-2 الكبدي العصاري وليس لـ P-glycoprotein.",
  en: "Efflux transporter fallacy: Isoniazid is rapidly and completely absorbed; phenotypic clearance divergence is strictly driven by allelic variants of hepatic cytosolic NAT-2."
};

lesson.steps[6].conceptCheck.options[2].text = {
  tr: "Hızlı asetilatörlerde CYP2E1 enzimi aşırı aktiftir; izoniyazid asetillenmek yerine mikrozomal hidroksilasyonla parçalanır.",
  ar: "يمتلك المفرزون السريعون نشاطاً مفرطاً لإنزيم CYP2E1؛ فيتفكك الإيزونيازيد بالأكسدة الميكروزومية بدلاً من الأسيتلة.",
  en: "Rapid acetylators express hyperactive CYP2E1 monooxygenases that rapidly clear isoniazid via Phase I aliphatic hydroxylation rather than acetylation."
};
lesson.steps[6].conceptCheck.options[2].misconceptionFeedback = {
  tr: "CYP oksidasyonu yanılgısı: İzoniyazidin majör eliminasyon yolu Faz I oksidasyonu değil, Faz II N-asetilasyonudur (NAT-2). CYP aktivitesi fenotipik temizlenme hızını belirlemez.",
  ar: "مغالطة أكسدة CYP: المسار الإقصائي الرئيسي للإيزونيازيد هو الأسيتلة بإنزيم NAT-2 وليس أكسدة CYP؛ نشاط CYP لا يحدد هذا التباين الظاهري.",
  en: "CYP oxidation misconception: Isoniazid primary clearance is governed by NAT-2 acetylation of its hydrazine moiety, not microsomal CYP monooxygenation."
};

// Step 8: Concept Check
lesson.steps[7].conceptCheck.options[1].text = {
  tr: "Sülfotransferaz (SULT); mitokondri iç zarında ATP sentaz ile kompleks halde bulunan mikrozomal bir enzimdir.",
  ar: "سلفوترانسفيراز (SULT)؛ إنزيم ميكروزومي مرتبط بإنزيم تصنيع ATP على الغشاء الداخلي للميتوكوندريا.",
  en: "Sulfotransferase (SULT); an integral membrane enzyme localized to the mitochondrial inner membrane alongside ATP synthase."
};
lesson.steps[7].conceptCheck.options[1].misconceptionFeedback = {
  tr: "SULT yerleşim yanılgısı: SULT enzimleri mitokondriyal veya membranöz değildir; hücre sitozolünde çözünmüş halde bulunurlar. Endoplazmik retikuluma gömülü tek majör Faz II enzimi UGT'dir.",
  ar: "مغالطة توضع SULT: إنزيمات SULT ذائبة في العصارة الخلوية وليست ميتوكوندرية؛ UGT هو الإنزيم الميكروزومي الوحيد المنغرس بالشبكة الإندوبلازمية.",
  en: "SULT localization misconception: SULT enzymes are soluble cytosolic proteins; UGT is the unique major Phase II transferase embedded in the endoplasmic reticulum."
};

lesson.steps[7].conceptCheck.options[2].text = {
  tr: "Glutatyon S-transferaz (GST); nükleer por kompleksine ve çekirdek zarına kalıcı olarak gömülü bir enzimdir.",
  ar: "جلوتاثيون إس ترانسفيراز (GST)؛ إنزيم منغرس بشكل دائم في الغلاف النووي ومعقد المسام النووية.",
  en: "Glutathione S-transferase (GST); an integral membrane protein embedded within the outer nuclear envelope and pore complexes."
};
lesson.steps[7].conceptCheck.options[2].misconceptionFeedback = {
  tr: "GST hücresel yerleşim yanılgısı: GST'nin majör detoksifikasyon izoformları sitozolde serbestçe dağılmıştır (küçük bir mikrozomal alt tip hariç); ER lümeninde yerleşik olan ve yüksek kapasiteli Faz II konjugasyonunu yöneten enzim UGT'dir.",
  ar: "مغالطة توضع GST: تتواجد نظائر GST بشكل أساسي حرة في العصارة الخلوية؛ بينما UGT هو الإنزيم الرئيسي المنغرس في تجويف الشبكة الإندوبلازمية.",
  en: "GST compartmentalization fallacy: Canonical GST enzymes are soluble cytosolic transferases; UGT is the hallmark microsomal enzyme anchored in the ER membrane."
};

// Step 9: Application
lesson.steps[8].conceptCheck.options[1].text = {
  tr: "NAC doğrudan CYP2E1 enziminin aktif bölgesine bağlanarak enzimi yarışmalı olarak inhibe eder ve parasetamolün oksidasyonunu durdurur.",
  ar: "يرتبط NAC مباشرة بالموقع الفعال لـ CYP2E1 ويثبطه تنافسياً ليوقف أكسدة الباراسيتامول تماماً.",
  en: "NAC binds directly to the CYP2E1 heme catalytic pocket, acting as a competitive inhibitor to arrest paracetamol oxidation."
};
lesson.steps[8].conceptCheck.options[1].misconceptionFeedback = {
  tr: "CYP inhibisyonu yanılgısı: NAC bir CYP2E1 inhibitörü değildir; kofaktör öncülü (L-sistein donörü) olarak hücre içi glutatyon (GSH) havuzunu yeniler ve tiyol grubuyla serbest NAPQI'yi redükler.",
  ar: "مغالطة تثبيط CYP: لا يثبط NAC إنزيم CYP2E1؛ بل يعمل كمانح للسيستين لتجديد مخزون الجلوتاثيون (GSH) واختزال NAPQI كيميائياً بمجموعة الثيول.",
  en: "CYP inhibition misconception: NAC does not inhibit CYP2E1; it serves as a bioavailable L-cysteine precursor to replenish depleted glutathione (GSH) pools."
};

lesson.steps[8].conceptCheck.options[2].text = {
  tr: "NAC gastrointestinal kanalda aktif kömür gibi davranarak parasetamol moleküllerini bağlar ve sistemik emilimi engeller.",
  ar: "يعمل NAC في السبيل الهضمي كالفحم النشط مشلباً جزيئات الباراسيتامول لمنع امتصاصها الجهازي.",
  en: "NAC functions as an intestinal chelating resin analogous to activated charcoal, binding paracetamol lumenally to prevent absorption."
};
lesson.steps[8].conceptCheck.options[2].misconceptionFeedback = {
  tr: "İntestinal şelasyon yanılgısı: NAC bir gastrointestinal bağlayıcı değildir; sistemik olarak emilip hepatosite girerek sistein sağlayan ve tükenen glutatyonu yeniden sentezleten metabolik bir antidottur.",
  ar: "مغالطة الارتباط الهضمي: لا يعمل NAC كراتنج رابط في الأمعاء؛ بل يُمتص جهازياً ليدخل الكبد ويوفر السيستين اللازم لإعادة بناء الجلوتاثيون.",
  en: "Intestinal binding fallacy: NAC is not an adsorbative resin; it is systemically absorbed and converted intracellularly into cysteine to rescue hepatic GSH."
};

// Step 10: Retrieval
lesson.steps[9].conceptCheck.options[1].text = {
  tr: "UGT: NADPH; SULT: ATP; NAT: Koenzim Q10 (Ubikinon).",
  ar: "UGT: NADPH؛ SULT: ATP؛ NAT: مرافق الإنزيم Q10.",
  en: "UGT: NADPH; SULT: ATP; NAT: Coenzyme Q10 (Ubiquinone)."
};
lesson.steps[9].conceptCheck.options[1].misconceptionFeedback = {
  tr: "Redoks ve biyoenerji kofaktörü yanılgısı: NADPH Faz I CYP enzimlerinin elektron donörüdür; ATP genel enerji molekülüdür. Faz II transferazları nükleotit bağlı aktif transfer kofaktörleri (UDPGA, PAPS, Asetil-KoA) kullanır.",
  ar: "مغالطة مرافقات الأكسدة والإرجاع: NADPH مانح إلكترونات لـ CYP في المرحلة الأولى وATP طاقة عامة؛ إنزيمات المرحلة الثانية تتطلب مرافقات نقل مخصصة (UDPGA, PAPS, Asetil-KoA).",
  en: "Redox cofactor confusion: NADPH supplies electrons for Phase I CYPs; Phase II transferases require specialized activated nucleotide donors (UDPGA, PAPS, Acetyl-CoA)."
};

lesson.steps[9].conceptCheck.options[2].text = {
  tr: "UGT: Glutatyon (GSH); SULT: S-Adenozilmetiyonin (SAM); NAT: Glisin.",
  ar: "UGT: جلوتاثيون (GSH)؛ SULT: إس-أدينوزيل ميثيونين (SAM)؛ NAT: جليسين.",
  en: "UGT: Glutathione (GSH); SULT: S-Adenosylmethionine (SAM); NAT: Glycine."
};
lesson.steps[9].conceptCheck.options[2].misconceptionFeedback = {
  tr: "Transferaz kofaktör eşleşme yanılgısı: Glutatyon GST'nin, SAM metiltransferazların (COMT), glisin ise açiltransferazın kofaktörüdür; UGT UDPGA, SULT PAPS, NAT ise Asetil-KoA gerektirir.",
  ar: "مغالطة خلط مرافقات النقل: الجلوتاثيون يخص GST، وSAM يخص COMT، والجليسين يخص ناقلات الأسيل؛ بينما تتطلب UGT/SULT/NAT كلاً من UDPGA وPAPS وأسيتيل-CoA.",
  en: "Transferase mismatched donor error: GSH belongs to GST, SAM belongs to methyltransferases (COMT), and glycine belongs to amino acid transferases, not UGT/SULT/NAT."
};

// Step 11: Connection
lesson.steps[10].conceptCheck.options[1].text = {
  tr: "Bakteriyel enzimler metenamin kafesini tanıyıp parçalayarak amonyak gazı üretir ve bakterileri aşırı alkali şokla yok eder.",
  ar: "تتعرف الإنزيمات البكتيرية على قفص الميثينامين وتفككه مولدة غاز الأمونيا الذي يقضي على البكتيريا بصدمة قلوية.",
  en: "Bacterial enzymes recognize and cleave the methenamine cage into ammonia gas, killing microorganisms via hyperalkaline osmotic shock."
};
lesson.steps[10].conceptCheck.options[1].misconceptionFeedback = {
  tr: "Bakteriyel enzim parçalanması yanılgısı: Metenaminin aktivasyonu enzimatik değildir; asidik idrar ortamında (pH < 5.5) spontan kimyasal hidrolizle açığa çıkan formaldehit bakterileri denatüre eder.",
  ar: "مغالطة التفكك بالإنزيمات البكتيرية: تنشيط الميثينامين غير إنزيمي إطلاقاً؛ بل يحدث بحلمهة كيميائية تلقائية في بول حمضي (pH < 5.5) محرراً الفورمالدهايد القاتل.",
  en: "Bacterial enzymatic cleavage fallacy: Methenamine activation is strictly non-enzymatic; spontaneous chemical hydrolysis in acidic urine (pH < 5.5) generates bactericidal formaldehyde."
};

lesson.steps[10].conceptCheck.options[2].text = {
  tr: "Alkali idrarda (pH > 8.0) metenamin hızla iyonize olur ve bakterilerin folik asit sentez pompalarını yarışmalı olarak kilitler.",
  ar: "يتأين الميثينامين في البول القلوي (pH > 8.0) ويثبط مضخات تصنيع حمض الفوليك البكتيرية تنافسياً.",
  en: "In alkaline urine (pH > 8.0), methenamine ionizes rapidly to competitively block bacterial folate synthesis uptake transporters."
};
lesson.steps[10].conceptCheck.options[2].misconceptionFeedback = {
  tr: "Alkali ortam ve folat yanılgısı: Metenamin alkali idrarda tamamen kararlıdır ve formaldehit açığa çıkaramaz; aktivasyon için mutlaka asidik pH (< 5.5) şarttır ve etki mekanizması folat inhibisyonu değil formaldehit protein denatürasyonudur.",
  ar: "مغالطة الوسط القلوي: الميثينامين خامل في البول القلوي؛ يتطلب تنشيطه وسطاً حمضياً (pH < 5.5) وآليته هي تمسخ البروتين بالفورمالدهايد لا تثبيط الفولات.",
  en: "Alkaline activation misconception: Methenamine is chemically stable in alkaline urine and cannot release formaldehyde; it strictly requires an acidic pH (< 5.5)."
};

// Step 12: Mastery Check
lesson.steps[11].conceptCheck.options[1].text = {
  tr: "16 mmol NAPQI hepatosit proteinlerine geri dönüşümlü bağlanır; CYP2E1 doyunca metabolit kendiliğinden kandan temizlenir ve nekroz önlenir.",
  ar: "يرتبط 16 ميليمول NAPQI ببروتينات الكبد عكوساً؛ وعند تشبع CYP2E1 يُطرح المستقلب تلقائياً من الدم دون حدوث نخر.",
  en: "The 16 mmol NAPQI binds hepatocyte proteins reversibly; once CYP2E1 saturates, excess metabolite clears spontaneously without causing necrosis."
};
lesson.steps[11].conceptCheck.options[1].misconceptionFeedback = {
  tr: "Geri dönüşümlü bağlanma yanılgısı: NAPQI elektrofilik bir kinonimindir; proteinlerin nükleofilik sistein tiyollerine kovalent (geri dönüşsüz) bağlanarak mitokondriyi çökertir ve masif nekroz başlatır.",
  ar: "مغالطة الارتباط العكوس: NAPQI مركب كينون إلكتروفيلي يرتبط تساهمياً (بشكل غير عكوس) مع مجموعات الثيول في بروتينات الكبد، مما يسبب تنخراً خلوياً شاملاً.",
  en: "Reversible binding misconception: NAPQI is an electrophilic benzoquinoneimine that forms irreversible covalent bonds with mitochondrial protein thiols, driving fulminant hepatic necrosis."
};

lesson.steps[11].conceptCheck.options[2].text = {
  tr: "10 mmol glutatyon katalitik bir enzim gibi çalışıp 16 mmol NAPQI'nin tamamını sıfırlar; GSH tükenmesi yaşanmaz ve karaciğer korunur.",
  ar: "يعمل 10 ميليمول جلوتاثيون كإنزيم حفاز لإبطال مفعول كامل الـ 16 ميليمول NAPQI دون أي استنزاف لـ GSH.",
  en: "The 10 mmol glutathione functions as a catalytic enzyme to neutralize all 16 mmol NAPQI repeatedly without undergoing consumable depletion."
};
lesson.steps[11].conceptCheck.options[2].misconceptionFeedback = {
  tr: "Katalitik glutatyon yanılgısı: GSH bir enzim değildir; NAPQI ile bire bir (1:1 stoikiometrik) tüketilen feda edilebilir bir tripeptittir. 10 mmol GSH bittiğinde kalan 6 mmol NAPQI hücreyi yok eder.",
  ar: "مغالطة الطبيعة الحفازة للجلوتاثيون: GSH ليس إنزيماً بل ركيزة ببتيدية تُستهلك بنسبة ستوكيومترية (1:1)؛ ونفاذ الـ 10 ميليمول يترك 6 ميليمول تدمر الخلايا.",
  en: "Catalytic glutathione misconception: GSH is a consumable tripeptide co-substrate consumed stoichiometrically 1:1; once depleted, excess electrophilic NAPQI devastates hepatocyte proteins."
};

// Mirror options into config.options
lesson.steps.forEach((s) => {
  if (s.conceptCheck?.options && s.config) {
    s.config.options = s.conceptCheck.options.map(opt => ({
      id: opt.id,
      text: opt.text?.tr || opt.text,
      isCorrect: opt.isCorrect,
      misconceptionFeedback: opt.misconceptionFeedback?.tr || opt.misconceptionFeedback
    }));
  }
});

fs.writeFileSync(lessonPath, JSON.stringify(lesson, null, 2), 'utf8');
fs.writeFileSync('c:/Users/hp/Documents/antigravity/valiant-raman/courses/medchem/lessons/lesson-10.json', JSON.stringify(lesson, null, 2), 'utf8');
console.log('Successfully polished all distractors in lesson-10.json and synced both workspaces!');
