/**
 * UI strings for the whiteboard tutor + dashboard. Turkish first, English kept (Arabic paused for the
 * pilot, falls back to Turkish). Kept out of locales/*.json on purpose: the i18n parity test requires
 * identical keys in tr/ar/en and Arabic is intentionally not being translated during the pilot.
 */
export type WbLocale = 'tr' | 'en';

const tr = {
  pilotBadge: 'Vizeye Hazırlık',
  draftBadge: 'Taslak: onay bekliyor',
  verifiedBadge: 'Onaylı',
  lecture: 'Ders',
  concept: 'Kavram',
  of: '/',
  loadingConcept: 'Kavram yükleniyor…',
  noConcepts: 'Bu ders için henüz yayınlanmış kavram yok.',
  backToDashboard: 'Panele dön',
  tutorTitle: 'Tahta Öğretmeni',
  tutorIdle: 'Görevi çöz. Takıldığında buradan yönlendireceğim.',
  tutorThinking: 'Düşünüyorum…',
  askHint: 'İpucu iste',
  retry: 'Tekrar dene',
  next: 'Sonraki kavram',
  finish: 'Dersi bitir',
  slide: 'Slayt',
  deck: 'Kaynak',
  sourceLadder: 'Ders notundan',
  sourceLlm: 'Yapay zekâ ifadesi',
  levelNudge: 'Dürtme',
  levelClue: 'İpucu',
  levelRemediation: 'Çözüm',
  levelMastery: 'Doğru',
  correctAnswerIs: 'Doğru seçenek',
  connLabel: 'Bağlantı',
  connConnected: 'canlı',
  connConnecting: 'bağlanıyor',
  connOffline: 'çevrimdışı mod',
  offlineNote: 'Sunucuya ulaşılamadı; ders notundaki hazır yönlendirmeler kullanılıyor.',
  guestNote: 'Giriş yapmadan çalışıyorsun: ilerlemen yalnızca bu cihazda saklanır.',
  summaryTitle: 'Ders tamamlandı',
  summarySources: 'Bu derste kullanılan kaynaklar',
  summaryMastery: 'Kavram hâkimiyeti',
  modelNotice: 'Yapay zekâ yalnızca onaylı ders notlarını kullanır. Emin değilsen slayta bak.',
  dashTitle: 'Çalışma Paneli',
  examCountdown: 'Farmasötik Kimya Vizesi',
  daysLeft: (n: number) => `${n} gün kaldı`,
  examToday: 'Sınav bugün',
  examPassed: 'Sınav tarihi geçti',
  examUnset: 'Sınav tarihini ayarla (VITE_MEDCHEM_EXAM_DATE)',
  readiness: 'Hazır oluş',
  readinessHint: 'Tüm kavramların ortalama hâkimiyeti',
  daily10: 'Günlük 10',
  daily10Desc: 'En zayıf 3 kavram + en yeni dersten devam. Yaklaşık 10 dakika.',
  daily10Start: 'Başla',
  daily10Empty: 'Şimdilik tekrar edilecek kavram yok.',
  catalog: 'Ders Kataloğu',
  conceptsCount: (n: number) => `${n} kavram`,
  open: 'Aç',
  weakest: 'En zayıf kavramlar',
  masteryPct: (n: number) => `%${n}`,
  notStarted: 'başlanmadı',
};

const en: typeof tr = {
  pilotBadge: 'Exam prep',
  draftBadge: 'Draft: awaiting review',
  verifiedBadge: 'Verified',
  lecture: 'Lecture',
  concept: 'Concept',
  of: '/',
  loadingConcept: 'Loading concept…',
  noConcepts: 'No published concepts for this lecture yet.',
  backToDashboard: 'Back to dashboard',
  tutorTitle: 'Whiteboard Tutor',
  tutorIdle: "Solve the task. I'll guide you here when you get stuck.",
  tutorThinking: 'Thinking…',
  askHint: 'Ask for a hint',
  retry: 'Try again',
  next: 'Next concept',
  finish: 'Finish lecture',
  slide: 'Slide',
  deck: 'Source',
  sourceLadder: 'From the lecture notes',
  sourceLlm: 'AI phrasing',
  levelNudge: 'Nudge',
  levelClue: 'Clue',
  levelRemediation: 'Solution',
  levelMastery: 'Correct',
  correctAnswerIs: 'Correct option',
  connLabel: 'Connection',
  connConnected: 'live',
  connConnecting: 'connecting',
  connOffline: 'offline mode',
  offlineNote: 'Server unreachable; using the prepared guidance from the lecture notes.',
  guestNote: 'You are working signed out: progress stays on this device only.',
  summaryTitle: 'Lecture complete',
  summarySources: 'Sources used in this lecture',
  summaryMastery: 'Concept mastery',
  modelNotice: 'The AI only uses approved lecture notes. If unsure, check the slide.',
  dashTitle: 'Study Dashboard',
  examCountdown: 'Medicinal Chemistry midterm',
  daysLeft: (n: number) => `${n} days left`,
  examToday: 'Exam is today',
  examPassed: 'Exam date has passed',
  examUnset: 'Set the exam date (VITE_MEDCHEM_EXAM_DATE)',
  readiness: 'Readiness',
  readinessHint: 'Average mastery across all concepts',
  daily10: 'Daily 10',
  daily10Desc: 'Your 3 weakest concepts + the newest lecture. About 10 minutes.',
  daily10Start: 'Start',
  daily10Empty: 'Nothing to review right now.',
  catalog: 'Lecture Catalog',
  conceptsCount: (n: number) => `${n} concepts`,
  open: 'Open',
  weakest: 'Weakest concepts',
  masteryPct: (n: number) => `${n}%`,
  notStarted: 'not started',
};

export const wbStrings = { tr, en };
export type WbStrings = typeof tr;

export function wbText(locale: string): WbStrings {
  return locale === 'en' ? en : tr;
}
